#pragma once

// 包含SimpleWindow所有头文件

#include "AbsoluteLayout.h"
#include "Alignment.h"
#include "App.h"
#include "Button.h"
#include "ButtonBase.h"
#include "Color.h"
#include "Control.h"
#include "Cursor.h"
#include "Dip.h"
#include "DockLayout.h"
#include "DockPanel.h"
#include "FillLayout.h"
#include "Font.h"
#include "ICtlColor.h"
#include "ILayout.h"
#include "Icon.h"
#include "Keys.h"
#include "Label.h"
#include "Layer.h"
#include "LayoutHost.h"
#include "Menu.h"
#include "MenuBase.h"
#include "MenuItem.h"
#include "MsgBox.h"
#include "Panel.h"
#include "Path.h"
#include "Point.h"
#include "ProcMsg.h"
#include "Property.h"
#include "Rect.h"
#include "RoutedEvent.h"
#include "RoutedEventArgs.h"
#include "Screen.h"
#include "Size.h"
#include "StackLayout.h"
#include "StackLayoutH.h"
#include "StackLayoutV.h"
#include "StackPanel.h"
#include "Thickness.h"
#include "UIElement.h"
#include "Utils.h"
#include "Window.h"
#include "WndBase.h"
#include "WndMsg.h"
#include "WrapLayout.h"
#include "WrapLayoutH.h"
#include "WrapLayoutV.h"
#include "WrapPanel.h"

// 启用视觉样式
#pragma comment(linker, "\"/manifestdependency:type='win32' \
name='Microsoft.Windows.Common-Controls' version='6.0.0.0' \
processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
