#include "Property.h"

_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(bool);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(float);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(double);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(int8_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(int16_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(int32_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(int64_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(uint8_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(uint16_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(uint32_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(uint64_t);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(std::string);
_SW_DEFINE_EXTERN_PROPERTY_TEMPLATE(std::wstring);
